final List<String> dropdownOptions = [
    "Abbott Memorial Hall",
    "Alper House",
    "Arley D. Cathey Learning Center",
    "Bartlett Dining Commons",
    "Becker Friedman Institute",
    "Biological Sciences Learning Center",
    "Blackstone Hall",
    "Bond Chapel",
    "Booth School of Business",
    "Burton-Judson Courts",
    "Campus North Residential Commons",
    "Cobb Lecture Hall",
    "Cochrane-Woods Art Center",
    "Comer Children’s Hospital",
    "Crown Family School",
    "Court Theatre",
    "Crerar Library",
    "Divinity School",
    "Eckhart Hall",
    "Edelstone Hall",
    "Edward H. Levi Hall",
    "Ellis Avenue Parking Garage",
    "Fermi Institute",
    "Foster Hall",
    "Gleacher Center",
    "Goodman Theatre Center",
    "Green Hall",
    "Harper Memorial Library",
    "Harris School of Public Policy",
    "Haskell Hall",
    "Henry Crown Field House",
    "Ida Noyes Hall",
    "International House",
    "William Eckhardt Research Center",
    "Judd Hall",
    "Kersten Physics Teaching Center",
    "Knapp Center for Biomedical Discovery",
    "Laird Bell Law Quadrangle",
    "Logan Center for the Arts",
    "MacLean Hall",
    "Mansueto Library",
    "Max Palevsky Residential Commons",
    "McGiffert Hall",
    "Mitchell Tower",
    "Oriental Institute Museum",
    "Quadrangle Club",
    "Ratner Athletics Center",
    "Regenstein Library",
    "Ricketts Laboratory",
    "Robie House",
    "Rockefeller Memorial Chapel",
    "Rosenwald Hall",
    "Ryerson Physical Laboratory",
    "Saieh Hall for Economics",
    "Searle Chemistry Laboratory",
    "Smart Museum of Art",
    "Snell-Hitchcock Hall",
    "South Campus Residence Hall",
    "South Woodlawn Residence Hall",
    "Stagg Field",
    "Stony Island Hall",
    "Stuart Hall",
    "Swift Hall",
    "The Midway Plaisance",
    "Walker Museum",
    "Wieboldt Hall",
    "William Rainey Harper Memorial Library",
    "Young Memorial Building"
];