import 'package:flutter/material.dart';

final Map<String, dynamic> stopPlaces = {
    'Harper Court (NE Corner)': [],
    '53rd St & Kenwood': [],
    'Kimbark Plaza (NE Corner)': [],
    'Ellis & 53rd St.': [],
    'Ellis Garage & Ratner Athletic (West)': ['Ratner', 'Smart Museum of Art'],
    'Ellis Ave & 57th St': ['Mansueto Library', "Eckhardt", "Kersten Physics Teaching Center", "Searle Chemical Labratory"],
    'Levi Hall (W)': ['Henry Hinds Laboratory for Geophysical Sciences', "Bookstore" 'Edward H. Levi Hall'],
    'Goldblatt Pavilion': ['Student Wellness Center', "Department of Medicine"],
    'Logan Center': ['Logan Center for the Arts', 'Researching Computing Center'],
    '60th St. & Ellis (SE Corner)':  ['Burton - Judson Courts', 'Crown Family School of Social Work, Policy, and Practice', 'Edelstone Center', 'Renee Granville Grossman Residential Commons'],
    '60th St. & Woodlawn Ave (SE Corner)': ['Institute for Mathematical and Statistical Innovation', 'Harris School of Public Policy', 'Woodlawn'],
    'Keller Center EB': ['Keller Center', 'Midway Plaisance Park'],
    'Press Building': ['University of Chicago Press', "Office of the University Registrar"],
    'Stony Island Parking Lot': [],
    '57th St & Metra (NB)': ['57th St. Metra'],
    'Lake Park & 55th St. (SE Corner)': [],
    'Wyler Pavilion': ['Wyler Pavilion'],
    'Bernard Mitchell Hospital': ['Bernard Mitchell Hospital'],
    '58th Street & Drexel': ['Bernard Mitchell Hospital', 'American School', 'Kovler Hall'],
    "Comer Children's Hospital": ["Comer Children's Hospital", 'John Crerar Library'],
    '57th Street & Drexel (NB)': ['Gordon Center for Integrative Science', 'Knapp Center for Biomedical Discovery', 'John Crerar Library'],
    'Drexel Garage': ['Research Computing Center', 'The University of Chicago Human Resources Department', 'University of Chicago: Department of Safety and Security'],
    'Apostolic Lot': [],
    'Kenwood & 63rd': [],
    'Reynolds Club': ['Reynolds Club', "Mitchell"],
    '57th St & Metra (SB)': ['57th St. Metra'],
    '59th St & Metra': ['59th St. Metra', 'International House'],
    'International House': ['International House'],
    'Keller Center WB': ['Keller Center', 'Midway Plaisance Park'],
    'Burton-Judson Courts (NE Corner)': [],
    'Levi Hall (E)': ['Henry Hinds Laboratory for Geophysical Sciences', "Bookstore" 'Edward H. Levi Hall'],
    'Max Palevsky Residential Commons (NE Corner)': [],
    'Ellis Garage & Ratner Athletic Center (East)': [],
    '55th Street & University': ['Campus North Residential Commons'],
    '55th Street & Blackstone': [],
    'Blackstone & 53rd': [],
    '53rd & Kimbark (WB)': [],
    'Booth School': ['Chicago Booth Harper Center', 'ISAC', 'Saieh Hall For Economics'],
    'Rockefeller Chapel': ['Rockefeller Memorial Chapel', 'Ida Noyes Hall'],
    'S Lake Park & E 53rd St': [],
    'S Lake Park Ave & E Hyde Park Blvd': [],
    'S Michigan Ave/Roosevelt': [],
    'E Randolph St & S Michigan Ave': [],
    'Gleacher Center': ['Gleacher Center'],
    'UCHICAGO Medicine - River East': ['UChicago Medicine River East'],
    'N (Upper) Wacker Dr & W Madison St': [],
    'S (Upper) Wacker Dr & W Adams St': [],
    'UCHICAGO Medicine - South Loop': ['UChicago Medicine South Loop'],
    'Roosevelt Station': [],
    'S Drexel Ave & 57th St': ['Gordon Center for Integrative Science', 'Knapp Center for Biomedical Discovery', 'John Crerar Library'],
    'Ronald McDonald House & Friend Center': ['Ronald McDonald House & Friend Center'],
    'Hyde Park Shopping Center (S)': ['Hyde Park Shopping Center'],
    '57th Street Metra Station (E)': ['57th St. Metra'],
    '59th St & Kimbark / Lab School': ['University of Chicago Laboratory Schools', 'Ida Noyes Hall'],
    '59th & Ellis': ['Wieboldt Hall', 'Harper Memorial Library', 'Goodspeed Hall'],
    '60th & Cottage Grove': [],
    'Law School (S)': ['Law School', 'Burton - Judson Courts', 'Crown Family School of Social Work, Policy, and Practice', 'Edelstone Center'],
};

//Daytime and Nightime route lists
final List<Map<String, dynamic>> daytimeRoutes = [
  {
    'label': '53RD Street Express', 
    'stops': [
    'Harper Court (NE Corner)',
    '53rd St & Kenwood',
    'Kimbark Plaza (NE Corner)',
    'Ellis & 53rd St.',
    'Ellis Garage & Ratner Athletic (West)',
    'Ellis Ave & 57th St',
    'Levi Hall (W)',
    'Goldblatt Pavilion',
    'Logan Center',
    '60th St. & Ellis (SE Corner)',
    '60th St. & Woodlawn Ave (SE Corner)',
    'Keller Center EB',
    'Press Building',
    'Stony Island Parking Lot',
    '57th St & Metra (NB)',
    'Lake Park & 55th St. (SE Corner)',
    ],
    'color': Colors.yellow,
    'abbreviation': '53RD',
    'info': 'Good for Downtown Hyde Park on 53rd and far-away university buildings',
    'times': 'Mon-Fri, 7am-6pm, 7am-8am every 30 min, 8am-10:30am every 15 minutes, 10:30am-6pm every 30 min'
  },
  {
    'label': 'Apostolic/Drexel',
    'stops': [
    'Goldblatt Pavilion',
    'Wyler Pavilion',
    'Bernard Mitchell Hospital',
    '58th Street & Drexel',
    "Comer Children's Hospital",
    '57th Street & Drexel (NB)',
    'Levi Hall (W)',
    'Drexel Garage',
    'Apostolic Lot',
    'Kenwood & 63rd',
    ],
    'color': Colors.orange,
    'abbreviation': 'AP/DX',
    'info': 'Good for the University hospital and places of worship',
    'times': 'Mon-Fri, 10am-12:30am, 10am-3pm every 15 min, 3pm-12:30am every 10 min'
  },
  {
    'label': 'Downtown Campus Connector',
    'stops': [
    'Rockefeller Chapel',
    'Goldblatt Pavilion',
    '55th Street & University',
    'S Lake Park & E 53rd St',
    'S Lake Park Ave & E Hyde Park Blvd',
    'S Michigan Ave/Roosevelt',
    'E Randolph St & S Michigan Ave',
    'Gleacher Center',
    'UCHICAGO Medicine - River East',
    'N (Upper) Wacker Dr & W Madison St',
    'S (Upper) Wacker Dr & W Adams St',
    'UCHICAGO Medicine - South Loop',
    'Roosevelt Station',
    ],
    'color': const Color.fromARGB(255, 13, 97, 16),
    'abbreviation': 'DCC',
    'info': 'Shuttle for downtown Gleacher Center and UChicago Medicine clinics with limited main campus stops',
    'times': 'Mon-Fri, 6:30am-10pm, every 20 minutes'
  },
  {
    'label': 'Friend Center/Metra',
    'stops': [
      'Goldblatt Pavilion',
      'Wyler Pavilion',
      'Bernard Mitchell Hospital',
      '58th Street & Drexel',
      "Comer Children's Hospital",
      'S Drexel Ave & 57th St',
      'Ellis Garage & Ratner Athletic Center (East)',
      'Ronald McDonald House & Friend Center',
      '55th Street & University',
      'Hyde Park Shopping Center (S)',
      '57th Street Metra Station (E)',
      '59th St & Metra',
    ],
    'color': Colors.brown,
    'abbreviation': 'FCM',
    'info': 'Goes through edges of campus, the shopping center, and Metra stations',
    'times': 'Mon-Fri, 7am-6pm, 7am-8am every 30 min, 8am-10:30am every 15 minutes, 10:30am-6pm every 30 min'
  },
  {
    'label': 'Midway Metra',
    'stops': [
        '57th St & Metra (SB)',
        '59th St & Metra',
        '59th St & Kimbark / Lab School',
        '59th & Ellis',
        'Goldblatt Pavilion',
        'Bernard Mitchell Hospital',
        '60th & Cottage Grove',
        'Logan Center',
        '60th St. & Ellis (SE Corner)',
        'Law School (S)',
        '60th St. & Woodlawn Ave (SE Corner)',
        'Keller Center EB',
        'Press Building',
        'Stony Island Parking Lot',
        '57th St & Metra (NB)'
    ],
    'color': const Color.fromARGB(255, 0, 128, 128),
    'abbreviation': 'MM',
    'info': 'Midway route that only operates during morning and evening rush. Best for Metra commuters',
    'times': 'Mon-Fri, 5:40am-9:40am, 3:30p-6:40pm'
  },
];

final List<Map<String, dynamic>> nighttimeRoutes = [
  {
    'label': 'Central',
    'stops': [
    'Reynolds Club',
    '57th St & Metra (SB)',
    '59th St & Metra',
    'International House',
    'Keller Center WB',
    'Burton-Judson Courts (NE Corner)',
    'Levi Hall (E)',
    'Max Palevsky Residential Commons (NE Corner)',
    'Ellis Garage & Ratner Athletic Center (East)',
    '55th Street & University',
    '55th Street & Blackstone',
    'Blackstone & 53rd',
    '53rd & Kimbark (WB)',
    'Booth School'
    ],
    'color': Colors.orange,
    'abbreviation': 'CEN',
    'info': 'Nighttime route for central campus (goes to Downtown Hyde Park!)',
    'times': 'Every day, 4pm-4am, every 15-30 min'
  },
];